{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import getpass # import de la bibliothèque getpass qui demande un mot de passe\n",
    "import hashlib # import de la bibliothèque hashlib qui permet un hachage sécurisé du mot de passe\n",
    "import csv # import de la bibliothèque csv qui implémente des classes pour lire et écrire des données tabulaires au format CSV\n",
    "\n",
    "\n",
    "### Etape de Vérification ###\n",
    "def Verification():\n",
    "    \"\"\"\n",
    "        Name: Verification\n",
    "        Objet: verifier si le fichier existe et s'il peut etre lu\n",
    "        Output: affiche si le fichier n'existe pas ou s'il ne peut pas etre lu et appel la fonction Creation_compte\n",
    "    \"\"\"\n",
    "    try :\n",
    "        fichier = open(\"Dictionnaire_pendu.txt\", \"r\")\n",
    "        on_continu = True\n",
    "    except IOError :\n",
    "        print(\"Le fichier ne peut être trouvé.\")\n",
    "        on_continu = False\n",
    "    if on_continu :\n",
    "        if (fichier.readable()):\n",
    "            on_continu = True\n",
    "            Creation_compte()\n",
    "        else :\n",
    "            on_continu = False\n",
    "            print(\"Le fichier ne peut être lu.\")\n",
    "\n",
    "\n",
    "\n",
    "def Creation_compte ():\n",
    "    \"\"\"\n",
    "    Name : Creation_compte\n",
    "    Objet : Créer un compte utilisateur pour permettre de jouer\n",
    "    Output : Appel la fonction Authentification\n",
    "    \"\"\"\n",
    "    nom_utilisateur1 = input(\"Choisissez un nom d'utilisateur : \")\n",
    "    mdp = getpass.getpass (\"Choisissez votre mot de passe : \").encode('utf8') # Affiche une demande de mot de passe sans renvoyer d'écho\n",
    "    mdpc = hashlib.sha224(mdp).hexdigest() # Renvoie une chaîne de caractère contenant seulement des chiffres hexadécimaux\n",
    "    ok = input (\"Ecrivez ok en toutes lettres : \")\n",
    "    if ok != \"ok\":\n",
    "        print(\"Veuillez saisir ok\")\n",
    "        Creation_compte()\n",
    "    refresh = \"yes\"\n",
    "    compteur = 0\n",
    "    Identification (nom_utilisateur1, mdp, mdpc, ok, refresh, compteur)\n",
    "\n",
    "#### Enregistrement des données saisies dans un fichier csv ####\n",
    "    with open('Stockage_données.csv', 'a', newline='') as csvfile:\n",
    "        spamwriter = csv.writer(csvfile, delimiter='|',\n",
    "                                quotechar='|', quoting=csv.QUOTE_MINIMAL)\n",
    "        spamwriter.writerow([nom_utilisateur1] + [mdpc])\n",
    "\n",
    "\n",
    "#### Identification de l'utilisateur ####\n",
    "def Identification (nom_utilisateur1, mdp, mdpc, ok, refresh, compteur):\n",
    "    \"\"\"\n",
    "        Name: Identification\n",
    "        Objet: permet l'identification du joueur\n",
    "        Input : 6 args de type str, int, string, string, string, int\n",
    "        Output: verifie si le nom d'utilisateur et le mot de passe coincide avec la creation du compte\n",
    "    \"\"\"\n",
    "    while ok == \"ok\" and refresh == \"yes\" :\n",
    "        print(\"\")\n",
    "        print (\"==== Identification ====\")\n",
    "        print(\"\")\n",
    "        nom_utilisateur2 = input (\"Entrez votre nom d'utilisateur : \")\n",
    "        mdp1 = getpass.getpass (\"Tapez votre mot de passe : \").encode('utf8')\n",
    "        mdpc2 = hashlib.sha224(mdp1).hexdigest()\n",
    "        compteur = compteur + 1\n",
    "\n",
    "        if nom_utilisateur2 == nom_utilisateur1 and mdpc2 != mdpc :\n",
    "            print(\"\")\n",
    "            print (\"Ce n'est pas le bon mot de passe !\")\n",
    "\n",
    "        if nom_utilisateur2 != nom_utilisateur1 and mdpc2 == mdpc :\n",
    "            print(\"\")\n",
    "            print (\"Le nom d'utilisateur que vous avez entré n'est pas valide.\")\n",
    "\n",
    "        if nom_utilisateur2 != nom_utilisateur1 and mdpc2 != mdpc :\n",
    "            print(\"\")\n",
    "            print (\"Les deux identifiants sont incorrects.\")\n",
    "\n",
    "        if compteur == 3 :\n",
    "            print(\"\")\n",
    "            print (\"Vous avez essayé\", compteur, \"fois... vous n'avez plus d'essais\")\n",
    "            Creation_compte ()\n",
    "\n",
    "        if nom_utilisateur2 == nom_utilisateur1 and mdpc2 == mdpc :\n",
    "            print(\"\")\n",
    "            print (\"Vous avez mis les bons identifiants...\")\n",
    "            print(\"\")\n",
    "            print (\"Bon jeu\", nom_utilisateur2,\"!\")\n",
    "            print(\"\")\n",
    "            print(\"=======================================\")\n",
    "            mots_aleatoires()\n",
    "            break\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
